CREATE TABLE "homePageContent" (
	"id" serial PRIMARY KEY NOT NULL,
	"heroImageURL" text DEFAULT '' NOT NULL,
	"heroImageAlt" text DEFAULT 'Ancient Bhutanese Temple' NOT NULL,
	"heroHeadingLine1" text DEFAULT 'Walk the Ancient Paths:' NOT NULL,
	"heroHeadingLine2" text DEFAULT 'Bhutan Pilgrimage Through the Ages' NOT NULL,
	"heroParagraph" text DEFAULT 'Discover pilgrimages steeped in history...' NOT NULL,
	"heroButtonText" text DEFAULT 'Explore Our Sacred Routes' NOT NULL,
	"introHeading" text DEFAULT 'Ancient Tradition, Timeless Journey' NOT NULL,
	"introParagraph1" text DEFAULT 'Sacred Bhutan Travels invites you...' NOT NULL,
	"introParagraph2" text DEFAULT 'Each pilgrimage follows routes...' NOT NULL,
	"featuredHeading" text DEFAULT 'Our Sacred Journeys' NOT NULL,
	"featuredMapURL" text DEFAULT '' NOT NULL,
	"featuredMapAlt" text DEFAULT 'Vintage-style map of Bhutan' NOT NULL,
	"featuredMapCaption" text DEFAULT 'Ancient cartography revealing...' NOT NULL,
	"featuredButtonText" text DEFAULT 'View All Pilgrimages' NOT NULL,
	"carouselHeading" text DEFAULT 'Moments from Our Journeys' NOT NULL,
	"whyHeading" text DEFAULT 'Why Journey With Us' NOT NULL,
	"why1Icon" text DEFAULT '☸' NOT NULL,
	"why1Title" text DEFAULT 'Guardians of Tradition' NOT NULL,
	"why1Text" text DEFAULT 'Our guides are descendants...' NOT NULL,
	"why2Icon" text DEFAULT '📜' NOT NULL,
	"why2Title" text DEFAULT 'Deep Historical Knowledge' NOT NULL,
	"why2Text" text DEFAULT 'Each journey is enriched...' NOT NULL,
	"why3Icon" text DEFAULT '🤝' NOT NULL,
	"why3Title" text DEFAULT 'Authentic Encounters' NOT NULL,
	"why3Text" text DEFAULT 'We create meaningful connections...' NOT NULL,
	"testimonialsHeading" text DEFAULT 'Pilgrim Chronicles' NOT NULL,
	"updatedAt" timestamp DEFAULT now()
);
